safe: true
lsi: false
pygments: true
markdown: redcarpet
paginate: 10
title: Redbeacon Product Engineering Blog
#paginate_path: "blog/page:num"
#permalink: /blog/:year/:month/:day/:title
redcarpet:
    extensions:
        - hard_wrap
        - no_intra_emphasis
        - autolink
        - strikethrough
        - fenced_code_blocks
